plugins:
  layouts_sidebar_left_enabled:
    client: true
    type: list
    default: ''
    choices:
     - latest
     - new
     - unread
     - top
     - category
     - categories
     - topic
     - tags
  layouts_sidebar_right_enabled:
    client: true
    type: list
    default: ''
    choices:
     - latest
     - new
     - unread
     - top
     - category
     - categories
     - topic
     - tags
  layouts_sidebar_left_widgets:
    client: true
    default: ''
    type: list
    default: ''
    choices: []
  layouts_sidebar_right_widgets:
    client: true
    type: list
    default: ''
    choices: []
  layouts_sidebar_left_widgets_pinned_bottom:
    client: true
    default: ''
    type: list
    default: ''
    choices: []
  layouts_sidebar_right_widgets_pinned_bottom:
    client: true
    type: list
    default: ''
    choices: []
  layouts_sidebar_left_widgets_pinned_top:
    client: true
    default: ''
    type: list
    default: ''
    choices: []
  layouts_sidebar_right_widgets_pinned_top:
    client: true
    type: list
    default: ''
    choices: []
  layouts_sidebar_user_selected_widgets:
    client: true
    default: false
  layouts_sidebar_left_width:
    client: true
    default: 250
  layouts_sidebar_right_width:
    client: true
    default: 250
  layouts_sidebar_left_fixed:
    client: true
    default: true
  layouts_sidebar_right_fixed:
    client: true
    default: true
  layouts_list_navigation_disabled:
    client: true
    type: list
    default: ''
    choices:
     - latest
     - new
     - unread
     - top
     - category
     - categories
     - tags
  layouts_list_header_disabled:
    client: true
    type: list
    default: ''
    choices:
     - latest
     - new
     - unread
     - top
     - category
     - categories
  layouts_list_nav_menu:
    client: true
    type: list
    default: ''
    choices:
     - latest
     - new
     - unread
     - top
     - category
     - categories
